<?php

namespace Sp\CarManagementBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Sp\CarManagementBundle\Entity\Car;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{
    public function addCar($car, $categoryId){
        $car->setCategory($this->_em->getRepository('CarManagementBundle:Category')->find($categoryId));

        $this->_em->persist($car);
        $this->_em->flush();
    }

    public function editCar($carId, $newCarData, $newCategoryId){
        $car = $this->_em->getRepository('CarManagementBundle:Car')->find($carId);
        $car->setBrand($newCarData->getBrand());
        $car->setYear($newCarData->getYear());
        $car->setModel($newCarData->getModel());
        $car->setFueltype($newCarData->getFueltype());
        $car->setPriceperday($newCarData->getPriceperday());
        $car->setStatus($newCarData->getStatus());
        $car->setCategory($this->_em->getRepository('CarManagementBundle:Category')->find($newCategoryId));

        $this->_em->flush();
    }

    public function removeCar($id){
        $this->_em->remove($this->_em->getRepository('CarManagementBundle:Car')->find($id));
        $this->_em->flush();
    }
}
