#1.1: Criar um Dockerfile que:
#Tenha por base a imagem Ubuntu
#Execute os comandos:
#apt-get update
#instale o apache2 usando o comando apt-get e a opção -y
#Copie o ficheiro index.html para dentro da pasta /var/www/html
#	TIP: consultar slide 12
#1.2: Fazer o build da Imagem utilizando o Dockerfile anteriormente criado.
#	TIP: consultar slide 13
#1.3: Inicializar o Container a partir da imagem criada anteriormente, mapeando a porta 9000 do host para a porta 80 do Container e #usado as opções i, t e d.
#TIP: consultar slide 13
#1.4 Aceder através do browser, localhost:9000.
#1.5 Verificar o Id do Container.
#	TIP: consultar slide 14
#1.6 Parar e remover o Container.
#	TIP: consultar slide 15










ENTRYPOINT /usr/sbin/apache2ctl -D FOREGROUND
