#1.1: Criar um Dockerfile que:
#Tenha por base a imagem Ubuntu
#Execute os comandos:
#apt-get update
#instale o apache
#	TIP: consultar slide 12
#1.2: Fazer o build da Imagem utilizando o Dockerfile anteriormente criado.
#	TIP: consultar slide 13
#1.3: Inicializar o Container a partir da imagem anteriormente criada  mapeando a porta 9000 do host para a porta 80 do Container, montando o directório html no directório /var/www/html do Container e usado as opções i, t e d.
#TIP: consultar slide 13
#1.4 Aceder através do browser ao endereço localhost:9000.
#1.5 Efectuar uma alteração ao ficheiro index.html e voltar a aceder através do browser ao endereço localhost:9000. 